homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
import taxonomy
import os
import json
import requests
from random import choice

# Create your views here.
def index(request):
    return render(request, 'homepage.html')

def search(request):
    # Load Animal Suggestion TXT File
    with open("./Animal-words.txt") as f:
        suggest = f.read()
    suggest = suggest.split("\n")
    suggest = choice(suggest)

    response = {'name' : '' , 'wiki_id' : '','suggest' : suggest}
    if request.method == "POST":
        query = request.POST['animal']
        #If user inputs keyword, then we will search it directly from Wikidata
        if query[0] != "Q" and not str.isdigit(query[1:]):
            found = False
            search_api = requests.get("https://www.wikidata.org/w/api.php?action=query&list=search&srsearch=" + request.POST['animal'] + "&utf8=&format=json")
            search = json.loads(search_api.text)['query']['search']
            for i in search:
                if taxonomy.hasTaxonomyData(i['title']):
                    query = i['title']
                    found = True
                    break
        
            if not found:
                # Search from a-z-animal
                az = requests.get("https://a-z-animals.com/animals/" + query).text
                
                if ("File Not Found" in az or "Scientific Name</a>" not in az):
                    return render(request, 'not-found.html')

                az = az.split("Scientific Name</a>")[1]
                az = az.split("<td>")[1]
                az = az.split("</td>")[0]
                az = az.split(",")[0]
                query = az.replace(" ","+")

                # Match it again with wikidata
                search_api = requests.get("https://www.wikidata.org/w/api.php?action=query&list=search&srsearch=" + query + "&utf8=&format=json")
                search = json.loads(search_api.text)['query']['search']
                for i in search:
                    if taxonomy.hasTaxonomyData(i['title']):
                        query = i['title']
                        print("Has Taxon :" ,taxonomy.hasTaxonomyData(i['title']))
                        found = True
                        break

        #Implementing Cache for better performance
        try:
            os.mkdir("./cache")
        except:
            pass
        cache_path = "./cache/" + query + ".json"
        if os.path.isfile(cache_path):
            with open(cache_path) as f:
                response = json.load(f)
        else:
            response = taxonomy.animalData(query)
            with open(cache_path,"w+") as f:
                f.write(json.dumps(response))
            
        response['wiki_id'] = query

        #Forward Chaining
        #by Fransiscus Emmanuel Bunaren

        #Populate Rules
        rules = dict()
        
        rules["taxon_cephalopod | taxon_bivalvia"] = ["lives underwater"]

        rules["taxon_carnivora"] = ["eat meat"]
        rules["eat meat"] = ["have fangs"]

        rules["taxon_mammal"] = ["have mammary glands"]
        rules["have mammary glands"] = ["breastfeed its children"]
        rules["breastfeed its child"] = ["produce milk"]

        rules["taxon_vertebrata"] = ["have backbone"]
        rules["have backbone"] = ["have kidneys","have endoskeleton"]
        rules["have kidneys"] = ["have meat"]

        rules["taxon_primates"] = ["have two hands", "have two legs", "eat meat", "eat plants"]
        rules["eat plants"] = ["have molar teeth"]

        rules["taxon_bird"] = ["have wings", "lay eggs", "have fur"]
        rules["have wings"] = ["can fly"]

        rules["taxon_reptilia"] = ["lay eggs", "have scales", "are cold-blooded"]

        rules["taxon_toxicofera"] = ["are venomous"]
        rules["are venomous"] = ["are dangerous"]
        rules["taxon_dinosaur"] = ["are dinosaurs"]
        rules["are dinosaurs"] = ["are extinct"]

        rules['taxon_arachnida'] = ["have eight appendages"]
        rules["have eight appendages"] = ['have exoskeleton','eat insects','have mandibles']

        rules['taxon_insect'] = ['have mandibles','have exoskeleton','have no backbone']
        rules['have no backbone'] = ['have no kidneys']

        rules['taxon_crustacea'] = ['have exoskeleton','have a pair of antennae']

        rules['taxon_decapoda'] = ['have 5 pair of limbs']

        rules['taxon_octopoda'] = ['have 4 pair of limbs']

        rules['taxon_cephalopod'] = ["have arms/tentacles attached to it's head", 'can squirt ink when threatened']

        rules['taxon_amphibia'] = ['can live both on land and in water','goes through metamorphosis stages']

        rules['taxon_serpentes'] = ['moves using its belly','has no legs']

        #Advanced Rules (using operators)
        rules["taxon_tetrapoda & !taxon_serpentes"] = ["have four limbs"]
        
        #Populate Facts
        facts = ["taxon_" + i['value'].lower() for i in response['taxon']]
        explored_facts = []
        
        new_facts = 1
        #Rules with operators
        #It can handle negation (!), AND (&) , OR (|)
        for tmp_i in rules:
            if (" | " in tmp_i) or (" & " in tmp_i) or (" ! " in tmp_i):
                if " & " in tmp_i:
                    valid = True
                    tmp = tmp_i.split(" & ")
                    for h in tmp:
                        if "!" == h[0] and h[1:] in facts:
                            valid = valid and False
                        elif "!" == h[0] and h[1:] in explored_facts:
                            valid = valid and False
                        elif h not in facts and "!" != h[0]:
                            valid = valid and False
                    if valid:
                        facts.append(rules[tmp_i])
                        new_facts += 1
                if " | " in tmp_i:
                    tmp = tmp_i.split(" | ")
                    for h in tmp:
                        if "!" == h[0] and h[1:] not in facts:
                            facts.append(rules[tmp_i])
                            new_facts += 1
                            continue
                        elif "!" == h[0] and h[1:] not in explored_facts:
                            facts.append(rules[tmp_i])
                            new_facts += 1
                            continue
                        elif h in facts:
                            facts.append(rules[tmp_i])
                            new_facts += 1
                            continue

        #Do inference without operators
        while new_facts:
            new_facts = 0
            while len(facts) > 0:
                i = facts.pop()
                if type(i) == list:
                    i = i[0]
                #Add facts to explored_facts
                explored_facts.append(i)
                if i in rules:
                    for k in rules[i]:
                        #Iterate each rules
                        if k not in facts and k not in explored_facts:
                            facts.append(k)
                            new_facts += 1
        
        #Collect all the facts into list
        response['facts'] = [response['name'] + "s " + i for i in explored_facts if "taxon_" not in i]
        for i in facts:
            response['facts'].append(response['name'] + " " + i)

    response['suggest'] = suggest
    return render(request, 'search.html',response)

homepage/templates/homepage.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'custom.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Catamaran" rel="stylesheet">
  <link rel="icon" href="{% static 'undraw_unicorn_dp2f.svg' %}" type="image/gif" sizes="16x16">

</head>

<body style="overflow-x:hidden; background-image: linear-gradient(to right, #9fb8ad 0%, #1fc8db 51%, #2cb5e8 75%);">
	
	<div class="row">
		<div class="col-sm-5 section">
			<img class="homeImage" src="{% static 'undraw_unicorn_dp2f.svg' %}">
		</div>
		<div class="col-sm-7 section" style="padding-right:5vw;">
			<h1 class="title">Dataxon</h1>
			<div class="line"></div>
			<p class="text" style="text-align: justify;">
				Dataxon is a program that imports data from WikiData's articles, specifically
				the animal section. This app can infer the characteristics of animals listed in WikiData.
				Curious about the animals you just saw at the zoo? Check! Want to research your favorite
				animal? We got it all covered!
			</p>
			<br>
			<a class="startBtn btn-primary" href="{% url 'homepage:search' %}" role="button" style="margin-left: 11.5%;padding: 0 20px 0 20px;">Start</a>
		</div>
	</div>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

homepage/templates/not-found.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <title>Search Animal</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'custom.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Catamaran" rel="stylesheet">
  <link rel="icon" href="{% static 'undraw_unicorn_dp2f.svg' %}" type="image/gif" sizes="16x16">

</head>

<body style="overflow-x:hidden; background-image: linear-gradient(to right, #9fb8ad 0%, #1fc8db 51%, #2cb5e8 75%);">
    
    <br><br>
    <h class="font-weight-bold" style="font-size: 5vh; margin-left: 9.5%;">What characteristics does this animal have?</h>
	<br><br>
    <form method="post" action="/search/">
        {% csrf_token %}
        <div style="margin-left: 10px; margin-right: 10px;">
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <div class="form-group">
                    <label for="name">Animal's wikidata id / name / scientific name:</label>
                    <input class="form-control" id="animal" type="text" name="animal" maxlength="255" required placeholder="Q269728" value="{% if wiki_id %} {{ wiki_id }} {% endif %}">
                </div>
            </div>
        </div>
        <div class="form-row">
            <input name="submit" id="submitBtn" type="submit" class="btn btn-secondary" style="margin-left: 9.2%;" value="Submit">
        </div>
      </form>

        <!-- Displaying Animal Data by Fransiscus Emmanuel Bunaren -->
        <center/>
        <h2>
        Sorry, we can't find the animal that you want from wikidata. 
        Probably the keyword that you search does not exist in wikidata, or there is no taxonomy information about that keyword.
        </h2>

        <h3>
        <br/>We suggest you to :
        <br/>Change the keyword
        <br/>or simply type the Wikidata ID (Make sure that the data has "parent taxon" predicate)
        </h3>
        

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

homepage/templates/search.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <title>Search Animal</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'custom.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Catamaran" rel="stylesheet">
  <link rel="icon" href="{% static 'undraw_unicorn_dp2f.svg' %}" type="image/gif" sizes="16x16">

</head>

<style>
body{
	margin: auto;
	max-width: 900px;
    background-color:rgba(0,0,0,0);
}   
</style>

<script>
col_num = 0;
function random_rgba() {
    pastel_colors = ['#FF9AA2' ,'#FFDAC1','#E2F0CB','#B5EAD7', '#FFB7B2' ,'#C7CEEA']
    res = pastel_colors[col_num];
    col_num = (col_num + 1) % pastel_colors.length;
    return res;
}

</script>

<style>
td:nth-child(2) {
    padding-right: 100px;
}​
</style>

<html style="background-image:url(/static/bg.jpg);"/>

<body style="overflow-x:hidden;"> <!-- background-color:#F8D48E;" -->
    
    <br><br>
    
    <center>
    <div style="background-image: linear-gradient(141deg, #9fb8ad 0%, #1fc8db 51%, #2cb5e8 75%);color:white;border:1px solid white;">
        <h class="font-weight-bold" style="font-size: 5vh;">🦔 What characteristics does this animal have?</h>
	    <br><br><br>
    </div>

    <div style="background-color:white;">
        <form method="post" action="/search/">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-sm-1"></div>
                <div class="form-group col-sm-10">
                    <div class="form-group">
                        <label for="name">Animal's wikidata id / name / scientific name:</label>
                        <input class="form-control" id="animal" type="text" name="animal" maxlength="255" required placeholder="Manis javanica" value="{% if wiki_id %} {{ wiki_id }} {% endif %}">
                    </div>
                    <b>Suggestion</b> : Try Searching <a class="btn btn-success" style="padding:2px;" onclick="animal.value = '{{ suggest }}';"><font color="white">{{ suggest }}</font></a>
                </div>
            </div>
            <div class="form-row">
                <input name="submit" id="submitBtn" type="submit" class="submitBtn btn-primary" style="margin-left: 9.2%;" value="Submit">
            </div>
        </form>
    </div>

        <!-- Displaying Animal Data by Fransiscus Emmanuel Bunaren -->

        {% if name %}
        <table>
            <tr>
                <td class="polaroid">
                    <div class="card" style="width: 18rem;">
                        <center>
                            <img src="{{ image }}" alt="Card image cap" width="200px">
                        </center>
                        <div class="card-body">
                            <h5 class="card-title">{{ name }} ( {{ taxon_name }} )</h5>
                            <h5 class="card-title"></h5>
                            <p class="card-text">{{ description }}</p>

                            {% for info in taxon %}
                                <span class="rectangleLeft" style="color:white;">{{ info.label }}</span> <span class="rectangleRight" data-toggle="tooltip" title='{{ info.description }}'>{{ info.value }}</span><br/>
                            {% endfor %}
                        </div>
                        </div>
                    </div>
                </td>

                <td>&nbsp;</td>

                <td>
                    <div class="polaroid" style="width:350px">
                        <h2 style="background:#fbf063;">Inferred Facts</h2>
                        {% for fact in facts %}
                            <li/><big class="fact" style="font-size:24px;background-color:yellowgreen;"> {{ fact }} </big>
                        {% endfor %}
                    </div>
                </td>

        {% endif %}
        <br/><br/>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
<script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });


    facts = document.getElementsByClassName("fact");
    
    for (i =0 ; i< facts.length ;i++){
        tmp = random_rgba();
        facts[i].style.backgroundColor = tmp;
        facts[i].style.color = "black";
    }
</script>
</html>